/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-01-28 07:23:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class servicePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1705906252146L));
    _jspx_dependants.put("/WEB-INF/views/head.jsp", Long.valueOf(1705908628201L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1705904731582L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1705401830678L));
    _jspx_dependants.put("jar:file:/home/jongho/바탕화면/tomcat/apache-tomcat-9.0.85/wtpwebapps/CJU_Web_Application_Services/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<!-- 한글 적용 -->\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<!-- 한글 적용 -->\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<!-- 부트스트랩 적용 -->\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("	<!-- Jquery -->\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\" integrity=\"sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script> \n");
      out.write("	\n");
      out.write("	<title>청주대학교 STT 서비스</title>\n");
      out.write("	\n");
      out.write("</head>");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"d-flex h-100 text-center text-bg-dark\">\n");
      out.write("\n");
      out.write("<div class=\"cover-container d-flex w-100 h-100 p-3 mx-auto flex-column\">\n");
      out.write("  ");
      out.write("<!-- 한글 적용 -->\n");
      out.write("\n");
      out.write("<header class=\"mb-auto\">\n");
      out.write("    <div>\n");
      out.write("      <h3 class=\"float-md-start mb-0\">청주대학교 STT 서비스</h3>\n");
      out.write("      <nav class=\"nav nav-masthead justify-content-center float-md-end\">\n");
      out.write("        <a class=\"nav-link fw-bold py-1 px-0 active\" style=\"color:white\" href=\"/cju_stt\">Home</a>\n");
      out.write("        &nbsp; &nbsp;\n");
      out.write("        <a class=\"nav-link fw-bold py-1 px-0\" style=\"color:white\" href=\"https://www.cju.ac.kr/www/index.do\">청주대학교</a>\n");
      out.write("        &nbsp; &nbsp;\n");
      out.write("        <a class=\"nav-link fw-bold py-1 px-0\" style=\"color:white\" href=\"http://acin.cju.ac.kr/\">ACIN연구실</a>\n");
      out.write("      </nav>\n");
      out.write("    </div>\n");
      out.write("</header>");
      out.write("\n");
      out.write("\n");
      out.write("  <main class=\"px-3\">\n");
      out.write("    <h1 id=\"service_title\">변환을 시작합니다!</h1>\n");
      out.write("    <!-- action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" 폼 저장용 -->\n");
      out.write("    <hr>\n");
      out.write("    <form id=\"uploadForm\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("     <div class=\"container\" style=\"width:40%\">\n");
      out.write("		<label id=\"explan_text\" for=\"formFile\" class=\"form-label\">변환하실 음성파일을 넣어주세요.</label>\n");
      out.write("		<input class=\"form-control\" type=\"file\" name=\"file\">\n");
      out.write("	  </div>\n");
      out.write("	  </br>\n");
      out.write("     <input id=\"submit_button\" type=\"submit\" class=\"btn btn-lg btn-light fw-bold border-white bg-white\" value=\"변환 시작\" />\n");
      out.write("    </form>\n");
      out.write("    \n");
      out.write("    <textarea class=\"form-control\" id=\"typed-text\" rows=\"10\" style=\"display: none;\"></textarea>\n");
      out.write("  \n");
      out.write("  </main>\n");
      out.write("\n");
      out.write("  ");
      out.write("<!-- 한글 적용 -->\n");
      out.write("\n");
      out.write("<footer class=\"mt-auto text-white-50\">\n");
      out.write("    <p>청주대학교 인공지능소프트웨어 <a href=\"http://acin.cju.ac.kr/\" class=\"text-white\">ACIN연구실</a>, Developed by 신종호.</p>\n");
      out.write("</footer>");
      out.write("\n");
      out.write("  \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	function typeEffect(text, speed){\n");
      out.write("		 const element = document.getElementById('typed-text');\n");
      out.write("	  	 let i = 0;\n");
      out.write("	  	 const typingInterval = setInterval(function() {\n");
      out.write("	  		 element.innerHTML += text.charAt(i);\n");
      out.write("	  		 i++;\n");
      out.write("	  		 \n");
      out.write("	  		 if (i> text.lenght) {\n");
      out.write("	  			 clearInterval(typingInterval);\n");
      out.write("	  		 }\n");
      out.write("	  	 }, speed);\n");
      out.write("	 }\n");
      out.write("	\n");
      out.write("	function changePage() {\n");
      out.write("		$('#service_title').text(\"변환 결과\");\n");
      out.write("		$('#uploadForm').remove();\n");
      out.write("		$('#typed-text').show();\n");
      out.write("	}\n");
      out.write("	$(document).ready(function () {\n");
      out.write("		$(\"#uploadForm\").submit(function (event) {\n");
      out.write("			 event.preventDefault();\n");
      out.write("			 $('#submit_button').remove();\n");
      out.write("			 $('#service_title').text(\"작업 진행중...\");\n");
      out.write("			 $('#explan_text').text(\"파일 용량이 크면 오래걸리니 기다려주세요.\");\n");
      out.write("			 \n");
      out.write("			 \n");
      out.write("	        var formData = new FormData(this);\n");
      out.write("\n");
      out.write("	        $.ajax({\n");
      out.write("	            url: \"/cju_stt/upload\",\n");
      out.write("	            type: \"POST\",\n");
      out.write("	            data: formData,\n");
      out.write("	            processData: false,\n");
      out.write("	            contentType: false,\n");
      out.write("	            success: function (data) {\n");
      out.write("	            	  changePage();\n");
      out.write("	                var result = JSON.parse(data);\n");
      out.write("		            typeEffect(result.result, 50);\n");
      out.write("		            console.log(\"변환 성공!!\");\n");
      out.write("	            },\n");
      out.write("	            error: function (jqXHR, textStatus, errorThrown) {\n");
      out.write("	            	  console.log(\"AJAX 호출 실패\");\n");
      out.write("	                console.log(\"상태 코드: \" + jqXHR.status);\n");
      out.write("	                console.log(\"에러 타입: \" + textStatus);\n");
      out.write("	                console.log(\"에러 내용: \" + errorThrown);\n");
      out.write("	            }\n");
      out.write("	        });\n");
      out.write("		});\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/servicePage.jsp(16,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/upload");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
